services:
  postgresql_db:
    image: 'bitnami/postgresql'
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USERNAME}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
    networks:
      - portal-network
    volumes:
      - pgdata:/bitnami/postgresql

  api-java:
    build:
      context: .
    container_name: api-java
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgresql_db:5432/${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgresql_db
    networks:
      - portal-network


networks:
  portal-network:
    driver: bridge

volumes:
  pgdata: