version: '3.8'

services:
  portal-egresso-postgresql:
    image: 'bitnami/postgresql'
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USERNAME}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=db_portal_egresso