services:
  postgresql_db:
    image: 'bitnami/postgresql'
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USERNAME}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
    networks:
      - portal-network
    volumes:
      - pgdata:/bitnami/postgresql

  api-java:
    build:
      context: ./backend
    container_name: api-java
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgresql_db:5432/${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - WEB_APP_URL=http://localhost:5173
    depends_on:
      - postgresql_db
    networks:
      - portal-network

  web-app:
    build:
      context: ./web
      args:
        VITE_API_URL: http://localhost:8080
    container_name: web-app
    ports:
      - 5173:5173
    networks:
      - portal-network

networks:
  portal-network:
    driver: bridge

volumes:
  pgdata: