@url = http://localhost:8080

POST {{url}}/course
Content-Type: application/json

{
  "coordinatorId": "5cd546af-851e-439d-9a19-f71c3d52e461",
  "name": "Ciências da Computação",
  "level": "Graduação"
}

###

POST {{url}}/egress
Content-Type: application/json

{
  "name": "Gabriel",
  "email": "gabriel@example.com"
}

###

POST {{url}}/course/egress
Content-Type: application/json

{
  "courseId": "54cb9f64-12d4-424b-9cec-9dfb4b8f5be5",
  "egressId": "6924540e-70a8-4fb3-8029-bb36a0308b01",
  "startYear": 2010
}

###
POST {{url}}/egress/position
Content-Type: application/json

{
  "egressId": "6924540e-70a8-4fb3-8029-bb36a0308b01",
  "description": "Gerente de projeto",
  "location": "Google",
  "startYear": 2030
}

###

GET {{url}}/egress